### ISSUE TITLE
Please add "# encoding: utf-8" to the top of footnotes.rb

### ISSUE THREAD

**Issue by se4u** [orangejulius/jekyll-footnotes#1]
Line 54 of `footnotes.rb` contains a unicode character and the plugin crashes with this error

```
   .../jekyll-footnotes-0.6.1/lib/jekyll/footnotes.rb:54: 
  syntax error, unexpected $end, expecting keyword_end
  ..., @id)}\" class=\"backlink\">⏎</a></li>"
```

It can be fixed by specifying the encoding in the file.

**Comment by orangejulius** [comment]
Which version of Ruby are you using? My understanding is that UTF-8 has been the default encoding for quite some time (I think all of 2.x, but correct me if I'm wrong). I'd love to learn more if you have good resources to point to. Maybe it's a problem on only certain platforms?

**Comment by se4u** [comment]
Oh you are right,  my ruby version is too old. 
$ruby --version
  ruby 1.9.3p0 (2011-10-30 revision 33570) [x86_64-darwin10.8.0]
