### ISSUE TITLE
Links dont work in footnotes. 

### ISSUE THREAD

**Issue by se4u** [orangejulius/jekyll-footnotes#2]
Markdown links in footnotes don't seem to work. A workaround is to just write html but it would be nice if they worked by themself.

**Comment by orangejulius** [comment]
Thanks, I've been meaning to get to this for a while.

Can you try out [this change](https://github.com/orangejulius/jekyll-footnotes/pull/3) to see if that works for you?

**Comment by se4u** [comment]
Hi, I tried this update but it doesn't seem to be helping with this issue, here's a mwe in markdown 

```
---
---
<div id="coelho1992generalized"><pre>
    Author = {Coelho, Carlos A.},
    Title = {Generalized Canonical Analysis},
</pre></div>
{% footnotes %}
   {% fnbody %}
    it was [Coelho](#coelho1992generalized)  who first 
   {% endfnbody %}
{% endfootnotes %}
```

**Comment by orangejulius** [comment]
What's the HTML that is output for that footnote body? A similar test in my setup worked fine so I'd love to try to figure out what the difference is.

**Comment by se4u** [comment]
Here's a [gist with the html output](https://gist.github.com/se4u/84f696fb6bc0d7ac150d). 
It really just shows that the markdown is not being processed in my case which I guess could be an error on my side. Later I will try and see if I can fix this later because for now I just converted markdown to html urls manually. 

Thanks for all your help though.

**Comment by orangejulius** [comment]
Yeah, sounds like an issue with your config. I test changes in this gem by putting a line like the following in my jekyll site's gemfile:

```
gem 'jekyll-footnotes', path: '../jekyll-footnotes'
```

And then of course one has to carefully restart the jekyll server any time the footnotes code is changed. Let me know if that works for you, I'd love to get a second +1 before releasing a new version.

**Comment by se4u** [comment]
Just wanted to report that liquid tags in footnotes work perfectly. Although there processing might be handled separately. as you can see I am a noob at ruby/jekyll

**Comment by orangejulius** [comment]
I just finally pushed a new gem, 0.7.0, that should fix this. Let me know if it has any issues.
